(in-package #:clbsd)

;;; --------------------------------------------------------------------------
;;; Container struct — the core data model.
;;;
;;; Raw accessors use the %container- prefix (internal).  Public accessors
;;; are generated by DEFINE-CONTAINER-ACCESSOR: the reader delegates to the
;;; raw accessor; the writer additionally marks the struct dirty and signals
;;; the reconciler so it can converge actual state.
;;; --------------------------------------------------------------------------

(defstruct (container (:conc-name %container-)
                      (:copier nil))
  "A managed workload — either a FreeBSD jail or a Docker container
   running inside the Alpine Bhyve VM."
  (name       nil :type (or string null))
  (type       nil :type (or keyword null))    ; :jail | :docker
  (dataset    nil :type (or string null))
  (image      nil :type (or string null))     ; Docker image (nil for jails)
  (domain     nil :type (or string null))
  (port       nil :type (or integer null))
  (ip-addr    nil :type (or string null))     ; resolved at runtime
  (state      :stopped :type keyword)         ; :stopped | :running | :error
  (dirty-p    nil :type boolean)
  (callbacks  nil :type list))                ; a-list of keyword -> function

;; copy-container is intentionally provided via the raw defstruct mechanism.
;; We define it explicitly since we disabled :copier above to control naming.
(defun copy-container (c)
  "Return a shallow copy of container C."
  (make-container
   :name      (%container-name c)
   :type      (%container-type c)
   :dataset   (%container-dataset c)
   :image     (%container-image c)
   :domain    (%container-domain c)
   :port      (%container-port c)
   :ip-addr   (%container-ip-addr c)
   :state     (%container-state c)
   :dirty-p   (%container-dirty-p c)
   :callbacks (%container-callbacks c)))

;;; --- Accessor generation macro -------------------------------------------

(defmacro define-container-accessor (slot &key skip-signal)
  "Generate a public reader CONTAINER-<SLOT> and a writer (SETF CONTAINER-<SLOT>).
   The writer sets DIRTY-P to T and signals the reconciler unless SKIP-SIGNAL."
  (let ((public  (alexandria:symbolicate 'container- slot))
        (raw     (alexandria:symbolicate '%container- slot))
        (raw-dp  '%container-dirty-p))
    `(progn
       (defun ,public (c)
         ,(format nil "Read the ~A slot of container C." slot)
         (,raw c))
       (defun (setf ,public) (val c)
         ,(format nil "Write the ~A slot of container C.~@[~%Does NOT signal the reconciler.~]"
                  slot (when skip-signal t))
         (prog1 (setf (,raw c) val)
           ,@(unless skip-signal
               `((unless (%container-dirty-p c)
                   (setf (,raw-dp c) t))
                 (when (boundp '*reconciler-condvar*)
                   (signal-reconciler)))))))))

(define-container-accessor name      :skip-signal t)
(define-container-accessor type      :skip-signal t)
(define-container-accessor dataset   :skip-signal t)
(define-container-accessor image     :skip-signal t)
(define-container-accessor domain)
(define-container-accessor port)
(define-container-accessor ip-addr   :skip-signal t)
(define-container-accessor state)
(define-container-accessor dirty-p   :skip-signal t)
(define-container-accessor callbacks :skip-signal t)

;;; --- Lookup --------------------------------------------------------------

(defun find-container (name &optional (state *clbsd-state*))
  "Find a container by NAME in STATE (defaults to *clbsd-state*).
   Returns the container struct or NIL."
  (find name state :key #'container-name :test #'string=))
